In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr) #note to self: map that thing

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [14]:
A = np.random.randn(10)
A

array([-0.47903371,  0.30195392,  0.70792714,  0.31814359,  0.06088835,
        0.99171986,  0.01763325, -0.98676902,  0.45886208,  0.37501042])

In [11]:
B = np.random.randn(10)

In [15]:
B

array([-0.315103  ,  1.22033424,  0.81959825,  0.73958528,  0.0385012 ,
       -0.35878653,  0.07103612, -0.2190792 , -0.27357877, -0.72318339])

In [12]:
#binary functions (functions that use two arrays)
np.add(A, B)

array([-1.26372703, -0.15457135,  2.18965208,  1.72164561,  0.41126296,
       -0.27454127,  1.07391955, -0.72789091,  0.95767224,  0.67780498])

In [16]:
np.maximum(A, B)

array([-0.315103  ,  1.22033424,  0.81959825,  0.73958528,  0.06088835,
        0.99171986,  0.07103612, -0.2190792 ,  0.45886208,  0.37501042])

In [18]:
C = np.minimum(A,B)

In [19]:
C

array([-0.47903371,  0.30195392,  0.70792714,  0.31814359,  0.0385012 ,
       -0.35878653,  0.01763325, -0.98676902, -0.27357877, -0.72318339])